Project-Using-MVC-Identity/Hospital/Hospital.Web/Areas/Admin/Controllers/HospitalsController.cs
using Hospital.Services;
using Hospital.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hospital.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HospitalsController : Controller
    {
        private IHospitalInfo _hospitalInfo;

        public HospitalsController(IHospitalInfo hospitalInfo)
        {
            _hospitalInfo = hospitalInfo;
        }

        public IActionResult Index(int pageNumber = 1,int pageSize = 10)
        {
            return View(_hospitalInfo.GetAll(pageNumber,pageSize));
        }

        //CRUD Operation
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _hospitalInfo.GetHospitalById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(HospitalInfoViewModel vm)
        {
            _hospitalInfo.UpdateHospitalInfo(vm);
            return RedirectToAction("Index");   
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(HospitalInfoViewModel vm)
        {
            _hospitalInfo.InsertHospitalInfo(vm);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _hospitalInfo.DeleteHospitalInfo(id);
            return RedirectToAction("Index");
        }
    }
}

Project-Using-MVC-Identity/Hospital/Hospital.Web/Areas/Admin/Views/Hospitals/Index.cshtml
@using Hospitals.Utilities
@model PagedResult<Hospital.ViewModels.HospitalInfoViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Hello My name is kinal</h1>
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Type</th>
            <th>City</th>
            <th>PinCode</th>
            <th>Country</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Data)
        {
        <tr>    
             <td>@Html.DisplayFor(modelItem => item.Id)</td>
             <td>@Html.DisplayFor(modelItem => item.Name)</td>
             <td>@Html.DisplayFor(modelItem => item.Type)</td>
             <td>@Html.DisplayFor(modelItem => item.City)</td>
             <td>@Html.DisplayFor(modelItem => item.PinCode)</td>
             <td>@Html.DisplayFor(modelItem => item.Country)</td>
             <td>
                @Html.ActionLink("Edit", "Edit", new {id=item.Id}) @* id=item.PrimaryKey *@
                @Html.ActionLink("Details","Details",new{id=item.Id})
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
             </td>
        </tr>
        }
    </tbody>
</table>
<cs-pager es-paging-pagesize=Cint)Medel.PageSize
          es-paging-pagenumber=(int)odel.PageNunber
          cs-paging-totalitens=(int)Model.TotalItens
          cs-pagenumber-paran="pagetiumber"
          asp-controller="Hospitals"

          asp-action="Index"
          cs-pager-li-current-class="page-iten active"
          cs-pager-li-other-class="page-iten"
          cs-pager-li-non-active-class=*page-iten disabled"
          cs-pager-link-other-class="page-link">
</cs-pager>